version: "3.7"
services: 
  db:
    image: postgres
    env_file:
      - ./db.env
    ports:
      - "5432:5432"
  app:
    image: rise-backend-test
    env_file:
      - ./.env
    ports:
      - "3000:3000"