version: "3.7"
services: 
  db:
    image: postgres
    env_file:
      - ./db.env
    ports:
      - "5432:5432"
  app:
    image: 758465340169.dkr.ecr.us-east-1.amazonaws.com/rise-backend-test:latest
    env_file:
      - ./.env
    ports:
      - "3000:3000"